// Apple-like look: system font, iOS colors, soft radius, light gray canvas with white cards.
export const FONT = '-apple-system, BlinkMacSystemFont, "SF Pro Text", "SF Pro Display", "PingFang SC", "Segoe UI Variable Text", "Segoe UI", "Microsoft YaHei UI", "Helvetica Neue", Arial, sans-serif'

export const theme = {
  token: {
    fontFamily: FONT,
    fontSize: 14,
    colorPrimary: '#007AFF',
    colorInfo: '#007AFF',
    colorSuccess: '#34C759',
    colorWarning: '#FF9500',
    colorError: '#FF3B30',
    colorText: '#1D1D1F',
    colorTextSecondary: '#6E6E73',
    colorTextTertiary: '#86868B',
    colorBorder: '#D2D2D7',
    colorBorderSecondary: '#E8E8ED',
    colorBgLayout: '#F5F5F7',
    colorFillAlter: '#F5F5F7',
    borderRadius: 10,
    borderRadiusLG: 14,
    borderRadiusSM: 7,
    controlHeight: 34,
    controlHeightSM: 28,
    lineWidthFocus: 3,
    controlOutline: 'rgba(0, 122, 255, 0.22)',
    boxShadowSecondary: '0 10px 30px rgba(0,0,0,0.10), 0 2px 6px rgba(0,0,0,0.06)',
    motionDurationMid: '0.18s',
  },
  components: {
    Layout: { siderBg: 'transparent', bodyBg: '#F5F5F7', headerBg: 'transparent' },
    Menu: {
      itemBg: 'transparent', subMenuItemBg: 'transparent',
      itemColor: '#1D1D1F', itemHoverBg: 'rgba(0,0,0,0.045)',
      itemSelectedBg: 'rgba(0,122,255,0.12)', itemSelectedColor: '#007AFF',
      itemBorderRadius: 8, itemHeight: 34, itemMarginInline: 10, itemMarginBlock: 2,
      groupTitleColor: '#86868B', groupTitleFontSize: 11.5, iconSize: 15, activeBarBorderWidth: 0,
    },
    Card: { headerFontSize: 15, headerFontSizeSM: 14, headerHeightSM: 44, paddingLG: 22 },
    Button: { fontWeight: 500, primaryShadow: 'none', defaultShadow: 'none', dangerShadow: 'none', paddingInline: 16 },
    Table: { headerBg: 'transparent', headerColor: '#6E6E73', headerSplitColor: 'transparent', rowHoverBg: '#F5F5F7', borderColor: '#EEEEF0', cellPaddingBlockSM: 10 },
    Segmented: { trackBg: '#E8E8ED', itemSelectedBg: '#FFFFFF', borderRadius: 9 },
    Tag: { defaultBg: '#F2F2F7', defaultColor: '#3A3A3C' },
    Input: { activeShadow: '0 0 0 3px rgba(0,122,255,0.18)' },
    Select: { optionSelectedBg: 'rgba(0,122,255,0.10)' },
    Steps: { iconSize: 26 },
    Statistic: { contentFontSize: 30, titleFontSize: 13 },
    Alert: { borderRadiusLG: 12 },
  },
}
